# Form implementation generated from reading ui file 'd:\winkana\winkana.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(580, 440)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush
        )
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush
        )
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush
        )
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush
        )
        Form.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        Form.setFont(font)
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(20, 120, 120, 130))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(36)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet(
            "QPushButton {\n"
            "    background-color: #FFFFFF;\n"
            "    border: 2px solid #E5E5E5;\n"
            "    padding: 10px;\n"
            "    border-radius: 12px;\n"
            "    border-bottom: 4px solid #E5E5E5;\n"
            "    margin-bottom: 2px;\n"
            "}\n"
            "QPushButton:hover{\n"
            "    background-color: #F7F7F7;\n"
            "    border: 2px solid #E5E5E5;\n"
            "    padding: 10px;\n"
            "    border-radius: 12px;\n"
            "    border-bottom: 4px solid #E5E5E5;\n"
            "    margin-bottom: 2px;\n"
            "}\n"
            "QPushButton:pressed{\n"
            "    background-color: #D3F4FF;\n"
            "    border: 2px solid #88D8FF;\n"
            "    padding: 10px;\n"
            "    border-radius: 12px;\n"
            "    margin-bottom: 2px;\n"
            "    color: #1899D6;\n"
            "}\n"
            "QPushButton:checked{\n"
            "    background-color: #D3F4FF;\n"
            "    border: 2px solid #88D8FF;\n"
            "    padding: 10px;\n"
            "    border-radius: 12px;\n"
            "    border-bottom: 4px solid #88D8FF;\n"
            "    margin-bottom: 2px;\n"
            "    color: #1899D6;\n"
            "}"
        )
        self.pushButton.setCheckable(True)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(20, 10, 300, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(18)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 100, 50))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(36)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.combo = QtWidgets.QLabel(parent=Form)
        self.combo.setGeometry(QtCore.QRect(460, 20, 140, 40))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(18)
        font.setBold(False)
        self.combo.setFont(font)
        self.combo.setObjectName("combo")
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setGeometry(QtCore.QRect(0, 340, 581, 101))
        self.frame.setStyleSheet("QFrame {\n    background-color: #FFFFFF;\n}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setEnabled(True)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 340, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(18)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.continuebutton = QtWidgets.QPushButton(parent=self.frame)
        self.continuebutton.setGeometry(QtCore.QRect(410, 30, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        font.setBold(True)
        self.continuebutton.setFont(font)
        self.continuebutton.setStyleSheet(
            "QPushButton {\n"
            "    background-color: #58CC02;\n"
            "    padding: 10px;\n"
            "    border-radius: 16px;\n"
            "    border-bottom: 4px solid #58A700;\n"
            "    margin-bottom: 2px;\n"
            "    color: #FFFFFF\n"
            "}\n"
            "QPushButton:hover{\n"
            "    background-color: #61E002;\n"
            "    padding: 10px;\n"
            "    border-radius: 16px;\n"
            "    border-bottom: 4px solid #58A700;\n"
            "    margin-bottom: 2px;\n"
            "    color: #FFFFFF\n"
            "}\n"
            "QPushButton:pressed{\n"
            "    background-color: #61E002;\n"
            "    padding: 10px;\n"
            "    border-radius: 16px;\n"
            "    color: #FFFFFF\n"
            "}\n"
            "QPushButton:disabled{\n"
            "    background-color: #E5E5E5;\n"
            "    padding: 10px;\n"
            "    border-radius: 16px;\n"
            "    border: none;\n"
            "    color: #AFAFAF;\n"
            "}\n"
            ""
        )
        self.continuebutton.setObjectName("continuebutton")
        self.label_4 = QtWidgets.QLabel(parent=self.frame)
        self.label_4.setEnabled(True)
        self.label_4.setGeometry(QtCore.QRect(10, 45, 370, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(False)
        self.label_4.setFont(font)
        self.label_4.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading
            | QtCore.Qt.AlignmentFlag.AlignLeft
            | QtCore.Qt.AlignmentFlag.AlignTop
        )
        self.label_4.setObjectName("label_4")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_2.setGeometry(QtCore.QRect(160, 120, 120, 130))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(36)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet(
            "QPushButton {\n"
            "    background-color: #FFFFFF;\n"
            "    border: 2px solid #E5E5E5;\n"
            "    padding: 10px;\n"
            "    border-radius: 12px;\n"
            "    border-bottom: 4px solid #E5E5E5;\n"
            "    margin-bottom: 2px;\n"
            "}\n"
            "QPushButton:hover{\n"
            "    background-color: #F7F7F7;\n"
            "    border: 2px solid #E5E5E5;\n"
            "    padding: 10px;\n"
            "    border-radius: 12px;\n"
            "    border-bottom: 4px solid #E5E5E5;\n"
            "    margin-bottom: 2px;\n"
            "}\n"
            "QPushButton:pressed{\n"
            "    background-color: #D3F4FF;\n"
            "    border: 2px solid #88D8FF;\n"
            "    padding: 10px;\n"
            "    border-radius: 12px;\n"
            "    margin-bottom: 2px;\n"
            "    color: #1899D6;\n"
            "}\n"
            "QPushButton:checked{\n"
            "    background-color: #D3F4FF;\n"
            "    border: 2px solid #88D8FF;\n"
            "    padding: 10px;\n"
            "    border-radius: 12px;\n"
            "    border-bottom: 4px solid #88D8FF;\n"
            "    margin-bottom: 2px;\n"
            "    color: #1899D6;\n"
            "}"
        )
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_3.setGeometry(QtCore.QRect(300, 120, 120, 130))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(36)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet(
            "QPushButton {\n"
            "    background-color: #FFFFFF;\n"
            "    border: 2px solid #E5E5E5;\n"
            "    padding: 10px;\n"
            "    border-radius: 12px;\n"
            "    border-bottom: 4px solid #E5E5E5;\n"
            "    margin-bottom: 2px;\n"
            "}\n"
            "QPushButton:hover{\n"
            "    background-color: #F7F7F7;\n"
            "    border: 2px solid #E5E5E5;\n"
            "    padding: 10px;\n"
            "    border-radius: 12px;\n"
            "    border-bottom: 4px solid #E5E5E5;\n"
            "    margin-bottom: 2px;\n"
            "}\n"
            "QPushButton:pressed{\n"
            "    background-color: #D3F4FF;\n"
            "    border: 2px solid #88D8FF;\n"
            "    padding: 10px;\n"
            "    border-radius: 12px;\n"
            "    margin-bottom: 2px;\n"
            "    color: #1899D6;\n"
            "}\n"
            "QPushButton:checked{\n"
            "    background-color: #D3F4FF;\n"
            "    border: 2px solid #88D8FF;\n"
            "    padding: 10px;\n"
            "    border-radius: 12px;\n"
            "    border-bottom: 4px solid #88D8FF;\n"
            "    margin-bottom: 2px;\n"
            "    color: #1899D6;\n"
            "}"
        )
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_4.setGeometry(QtCore.QRect(440, 120, 120, 130))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(36)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet(
            "QPushButton {\n"
            "    background-color: #FFFFFF;\n"
            "    border: 2px solid #E5E5E5;\n"
            "    padding: 10px;\n"
            "    border-radius: 12px;\n"
            "    border-bottom: 4px solid #E5E5E5;\n"
            "    margin-bottom: 2px;\n"
            "}\n"
            "QPushButton:hover{\n"
            "    background-color: #F7F7F7;\n"
            "    border: 2px solid #E5E5E5;\n"
            "    padding: 10px;\n"
            "    border-radius: 12px;\n"
            "    border-bottom: 4px solid #E5E5E5;\n"
            "    margin-bottom: 2px;\n"
            "}\n"
            "QPushButton:pressed{\n"
            "    background-color: #D3F4FF;\n"
            "    border: 2px solid #88D8FF;\n"
            "    padding: 10px;\n"
            "    border-radius: 12px;\n"
            "    margin-bottom: 2px;\n"
            "    color: #1899D6;\n"
            "}\n"
            "QPushButton:checked{\n"
            "    background-color: #D3F4FF;\n"
            "    border: 2px solid #88D8FF;\n"
            "    padding: 10px;\n"
            "    border-radius: 12px;\n"
            "    border-bottom: 4px solid #88D8FF;\n"
            "    margin-bottom: 2px;\n"
            "    color: #1899D6;\n"
            "}"
        )
        self.pushButton_4.setCheckable(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.frame_2 = QtWidgets.QFrame(parent=Form)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 580, 440))
        self.frame_2.setStyleSheet(
            "QFrame{\n    background-color: rgba(255, 255, 255, 80%);\n}"
        )
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(90, 100, 381, 221))
        self.frame_3.setStyleSheet(
            "QFrame{\n"
            "    background-color: #FFFFFF;\n"
            "    border: 2px solid #E5E5E5;\n"
            "    padding: 10px;\n"
            "    border-radius: 16px;\n"
            "}"
        )
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_5 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 300, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(16)
        font.setBold(False)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border: none;\nbackground-color: none;")
        self.label_5.setObjectName("label_5")
        self.hiragana = QtWidgets.QPushButton(parent=self.frame_3)
        self.hiragana.setGeometry(QtCore.QRect(20, 70, 340, 50))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(14)
        font.setBold(True)
        self.hiragana.setFont(font)
        self.hiragana.setStyleSheet(
            "QPushButton {\n"
            "    background-color: #1CB0F6;\n"
            "    padding: 10px;\n"
            "    border-radius: 16px;\n"
            "    border-bottom: 4px solid #1899D6;\n"
            "    margin-bottom: 2px;\n"
            "    color: #FFFFFF\n"
            "}\n"
            "QPushButton:hover{\n"
            "    background-color: #1FC2FF;\n"
            "    padding: 10px;\n"
            "    border-radius: 16px;\n"
            "    border-bottom: 4px solid #1899D6;\n"
            "    margin-bottom: 2px;\n"
            "    color: #FFFFFF\n"
            "}\n"
            "QPushButton:pressed{\n"
            "    background-color: #1FC2FF;\n"
            "    padding: 10px;\n"
            "    border: none;\n"
            "    color: #FFFFFF\n"
            "}"
        )
        self.hiragana.setObjectName("hiragana")
        self.katakana = QtWidgets.QPushButton(parent=self.frame_3)
        self.katakana.setGeometry(QtCore.QRect(20, 140, 340, 50))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(14)
        font.setBold(True)
        self.katakana.setFont(font)
        self.katakana.setStyleSheet(
            "QPushButton {\n"
            "    background-color: #1CB0F6;\n"
            "    padding: 10px;\n"
            "    border-radius: 16px;\n"
            "    border-bottom: 4px solid #1899D6;\n"
            "    margin-bottom: 2px;\n"
            "    color: #FFFFFF\n"
            "}\n"
            "QPushButton:hover{\n"
            "    background-color: #1FC2FF;\n"
            "    padding: 10px;\n"
            "    border-radius: 16px;\n"
            "    border-bottom: 4px solid #1899D6;\n"
            "    margin-bottom: 2px;\n"
            "    color: #FFFFFF\n"
            "}\n"
            "QPushButton:pressed{\n"
            "    background-color: #1FC2FF;\n"
            "    padding: 10px;\n"
            "    border: none;\n"
            "    color: #FFFFFF\n"
            "}"
        )
        self.katakana.setObjectName("katakana")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "OpenDuolingo"))
        self.pushButton.setText(_translate("Form", "あ"))
        self.label.setText(
            _translate(
                "Form",
                '<html><head/><body><p><span style=" color:#3c3c3c;"><b>选择正确的假名</b></span></p></body></html>',
            )
        )
        self.label_2.setText(_translate("Form", "a"))
        self.combo.setText(_translate("Form", "0 Combo"))
        self.label_3.setText(
            _translate(
                "Form",
                '<html><head/><body><p><span style=" color:#58a700;">真棒！</span></p></body></html>',
            )
        )
        self.continuebutton.setText(_translate("Form", "检查"))
        self.label_4.setText(
            _translate(
                "Form",
                '<html><head/><body><p><span style=" color:#EA2B2B;">fuck</span></p></body></html>',
            )
        )
        self.pushButton_2.setText(_translate("Form", "あ"))
        self.pushButton_3.setText(_translate("Form", "あ"))
        self.pushButton_4.setText(_translate("Form", "あ"))
        self.label_5.setText(
            _translate(
                "Form",
                '<html><head/><body><p><span style=" color:#4b4b4b;"><b>请选择模式</b></span></p></body></html>',
            )
        )
        self.hiragana.setText(_translate("Form", "平仮名"))
        self.katakana.setText(_translate("Form", "片仮名"))
